# Problem 45
# 06 June 2003
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

class Triangle
  def self.[](n)
    n*(n+1)/2
  end
end

class Pentagonal
  def self.[](n)
    n*(3*n-1)/2
  end
end

class Hexagonal
  def self.[](n)
    n*(2*n-1)
  end
end

t = 285
p = 165
h = 143

puts [ t, p, h, Triangle[t] ].inspect

loop do
  h += 1
  while Triangle[t] < Hexagonal[h]
    t += 1
  end
  if Triangle[t] == Hexagonal[h]
    while Pentagonal[p] < Hexagonal[h]
      p += 1
    end
    break if Pentagonal[p] == Hexagonal[h]
  end
end

puts "T(#{t})=#{Triangle[t]}"
puts "P(#{p})=#{Pentagonal[p]}"
puts "H(#{h})=#{Hexagonal[h]}"

# [285, 165, 143, 40755]
# T(55385)=1533776805
# P(31977)=1533776805
# H(27693)=1533776805

# real	0m0.639s
# user	0m0.623s
# sys	0m0.008s
